app/urls.py
from django.urls import path
from .views import *

urlpatterns = [ 
    path('', index, name='index'),
    path('vacancy/', vacancy, name='vacancy'),
    path('person/', person, name='person'),
    path('tenders/', tenders, name='tenders'),
    path('finance/', financе, name='finance'),
    path('license/', license_view, name='license'),
    path('boshqaruv/', boshqaruv, name='boshqaruv'),
    path('structure/', structure, name='structure'),
    path('more_info/', more_info, name='more_info'),
    path('department/', department, name='department'),
    path('news/<slug:news_slug>/', news_detail, name='news_detail'),
    path('department/<slug:slug>/', department_detail, name='department_detail'),

]

development/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views

urlpatterns = i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

app/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from parler.models import TranslatableModel, TranslatedFields
from django.utils.text import slugify

class News(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(_('title'), max_length=200),
        description=models.CharField(_('description'), max_length=5200)
    )
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL') 
    logo = models.ImageField(upload_to='asia_logos/', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = _('New')
        verbose_name_plural = _('News')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.safe_translation_getter('title', any_language=True))
        super(News, self).save(*args, **kwargs)


class Person(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(_('name'), max_length=1500),
        department = models.CharField(_('department'), max_length=1500),
        share_capital = models.CharField(_('share_capital'), max_length=1500),
        share_fund = models.CharField(_('share_fund'), max_length=1500),
    )

    class Meta:
        verbose_name = _('Person')
        verbose_name_plural = _('Persons')

    def __str__(self):
        return self.name
    
class Tenders(TranslatableModel):
    translations = TranslatedFields(
        title =  models.CharField(_('title'), max_length=1000),
        description = models.TextField(_('description')),
    )
    pdf = models.FileField(upload_to='tenders/', null=True, blank=True) 
    start_time = models.DateField(null=True, blank=True)
    end_time = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name = _('Tender')
        verbose_name_plural = _('Tenders')
    
    def __str__(self):
        return f"{self.title} | {self.start_time}"

class License(models.Model):
    name = models.CharField(max_length=255)  # Имя лицензии
    pdf = models.FileField(upload_to='licenses/', null=True, blank=True) 

    class Meta:
        verbose_name = _('License')
        verbose_name_plural = _('Licenses')

    def __str__(self):
        return self.name




class Year(models.Model):
    year = models.PositiveIntegerField(verbose_name="Год") 
    
    class Meta:
        verbose_name = _('Year')
        verbose_name_plural = _('Years')

    def __str__(self):
        return str(self.year)


class FinancialData(TranslatableModel):
    translations = TranslatedFields(
        indicator_name = models.CharField(max_length=255, verbose_name=_("Показатель")),
        unit = models.CharField(max_length=50, verbose_name=_("Ед. изм."))
    )

    values = models.ManyToManyField(Year, through='FinancialYearData', )

    class Meta:
        verbose_name = _('FinancialData')
        verbose_name_plural = _('FinancialData')

    def __str__(self):
        return self.safe_translation_getter('indicator_name', any_language=True)


class FinancialYearData(models.Model):
    financial_data = models.ForeignKey(FinancialData, on_delete=models.CASCADE)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    value = models.CharField(max_length=200 , verbose_name="Значение", blank=True, null=True)

    class Meta:
        verbose_name = _('FinancialYearData')
        verbose_name_plural = _('FinancialYearData')

    def __str__(self):
        return f'{self.financial_data.safe_translation_getter("indicator_name", any_language=True)} - {self.year.year}'


class Management(TranslatableModel):
    translations = TranslatedFields(
        f_i_o = models.CharField(_('F_I_O'), max_length=1500),
        position = models.CharField(_('position'), max_length=1500),
        еducation = models.CharField(_('еducation'), max_length=1400),
        specialization = models.CharField(_('specialization'), max_length=1500),
        phone = models.CharField(_('phone'), max_length=1500),
        admission_date = models.CharField(_('admission_date'), max_length=1300),
        admission_time = models.CharField(_('admission_time'),max_length=1300 ),
    )
    img = models.ImageField(upload_to='management/', null=True, blank=True)

    class Meta:
        verbose_name = _('Management')
        verbose_name_plural = _('Managements')

    def __str__(self):
        return self.safe_translation_getter('f_i_o', any_language=True)


class MoreInfo(TranslatableModel):
    translations = TranslatedFields(
        title = models.CharField(_('title'), max_length=1500),
    )
    pdf = models.FileField(upload_to='more_info/', null=True, blank=True)
    pdf2 = models.FileField(upload_to='more_info/', null=True, blank=True)

    class Meta:
        verbose_name = _('MoreInfo')
        verbose_name_plural = _('MoreInfos')

    def __str__(self):
        return self.safe_translation_getter('title', any_language=True)
    

class Vacancy(TranslatableModel):
    translations = TranslatedFields(
        title = models.CharField(_('title'), max_length=1500),
        description = models.CharField(_('description'), max_length=1500),
    )
    phone = models.CharField(_('phone'), max_length=1500)

    class Meta:
        verbose_name = _('Vacancy')
        verbose_name_plural = _('Vacancies')

    def __str__(self):
        return self.safe_translation_getter('title', any_language=True)
    



class Department(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(_('title'), max_length=1500),
        descriptions=models.TextField(_('descriptions'), blank=True, null=True)
    )
    slug = models.SlugField(_('slug'), max_length=255, unique=True, blank=True, null=True)
    img = models.ImageField(upload_to='Department/', blank=True, null=True)

    def __str__(self):
        return self.safe_translation_getter('title', any_language=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            # Заполняем slug по индексу объекта
            self.slug = f'department-{self.id}' if self.id else None
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = _('Department')
        verbose_name_plural = _('Departments')

app/templates/boshqaruv.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<h2 id="boshqaruv" style="text-align: center; font-size: 60px;">{% trans "Jamiyatning ijro organi haqida ma'lumot" %}</h2>
<hr>
<div class="card-container">
  {% for managements in management %}
  <div class="card">
    <div class="card-image">
      <img src="{{ managements.img.url }}" alt="Toshev Nurxon Mirzayevich">
    </div>
    <div class="card-content">
      <div class="card-text">
        <h2>{% trans "Ijro organi a'zosi" %}</h2>
        <hr>
        <p><strong>F.I.O : </strong>{{ managements.f_i_o }}</p>
        <p><strong>Lavozimi: </strong>{{ managements.position }}</p>
        <p><strong>Ma'lumoti: </strong>{{ managements.еducation }}</p>
        <p><strong>Mutaxassisligi: </strong>{{ managements.specialization }}</p>
        <p><strong>Telefon raqam: </strong>{{ managements.phone }}</p>
        <p><strong>Qabul kuni: </strong>{{ managements.admission_date }}</p>
        <p><strong>Qabul soati: </strong>{{ managements.admission_time }}</p>
      </div>
    </div>
  </div>
  {% endfor %}


</div>



<style>
  .card {
    display: flex;
    flex-direction: column;
    max-width: 800px;
    margin: 20px auto;
    background-color: white;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    border-radius: 10px;
    overflow: hidden;
    /* Для обрезки изображений по углам */
  }

  .card-image {
    width: 100%;
  }

  .card-image img {
    width: 100%;
    height: auto;
    display: block;
  }

  .card-content {
    padding: 20px;
  }

  h2 {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 10px;
  }

  hr {
    border: 0;
    height: 2px;
    background-color: blue;
    margin-bottom: 15px;
  }

  p {
    font-size: 16px;
    line-height: 1.5;
    margin-bottom: 5px;
  }

  strong {
    font-weight: bold;
  }

  /* Адаптивное поведение для десктопов */
  @media (min-width: 768px) {
    .card {
      flex-direction: row;
      align-items: center;
    }

    .card-image {
      width: 40%;
      /* Изображение будет занимать 40% карточки */
    }

    .card-content {
      width: 60%;
      padding-left: 20px;
    }
  }
</style>

{% endblock %}

app/templates/department.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<style>
    .main_butt {
        display: grid;
        grid-template-columns: repeat(5, 1fr); /* Делает 5 колонок */
        gap: 20px; /* Расстояние между кнопками */
        padding: 20px;
    }

    .custom-button {
        position: relative;
        background-color: #27272a; /* bg-neutral-800 */
        height: 4rem; /* h-16 */
        width: 16rem; /* w-64 */
        border: 1px solid transparent; /* hover:border-rose-300 */
        text-align: left; /* text-left */
        padding: 0.75rem; /* p-3 */
        color: #f9fafb; /* text-gray-50 */
        font-size: 1rem; /* text-base */
        font-weight: 700; /* font-bold */
        border-radius: 0.5rem; /* rounded-lg */
        overflow: hidden;
        transition: all 0.5s ease; /* duration-500 */
    }

    .custom-button:hover {
        text-decoration: underline; /* hover:underline */
        text-underline-offset: 4px; /* hover:underline-offset-4 */
        text-decoration-thickness: 2px; /* hover:decoration-2 */
        color: #7181fb; /* hover:text-rose-300 */
    }

    .custom-button::before {
        content: '';
        position: absolute;
        width: 3rem; /* before:w-12 */
        height: 3rem; /* before:h-12 */
        right: 0.25rem; /* before:right-1 */
        top: 0.25rem; /* before:top-1 */
        background-color: #8b5cf6; /* before:bg-violet-500 */
        border-radius: 9999px; /* before:rounded-full */
        filter: blur(8px); /* before:blur-lg */
        transition: all 0.5s ease; /* before:duration-500 */
        z-index: 10;
    }

    .custom-button:hover::before {
        right: 3rem; /* hover:before:right-12 */
        bottom: 2rem; /* hover:before:-bottom-8 */
        box-shadow: 20px 20px 20px 30px #a21caf; /* hover:before:[box-shadow:...] */
    }

    .custom-button::after {
        content: '';
        position: absolute;
        width: 5rem; /* after:w-20 */
        height: 5rem; /* after:h-20 */
        right: 2rem; /* after:right-8 */
        top: 0.75rem; /* after:top-3 */

        border-radius: 9999px; /* after:rounded-full */
        filter: blur(8px); /* after:blur-lg */
        transition: all 0.5s ease; /* after:duration-500 */
        z-index: 10;
    }

    .custom-button:hover::after {
        right: -2rem; /* hover:after:-right-8 */
    }

    @media (max-width: 768px) {
        .main_butt {
            display: flex; /* Меняем grid на flex */
            flex-direction: column; /* Вертикальное расположение кнопок */
            align-items: center; /* Горизонтальное выравнивание по центру */
            justify-content: center; /* Вертикальное выравнивание по центру */
            height: 100vh; /* Высота контейнера на весь экран */
            gap: 20px; /* Оставляем расстояние между кнопками */

        }
        .image-text-container {
            flex-direction: column; /* Изменяем расположение на вертикальное */
            text-align: center; /* Выравниваем текст по центру */
            gap: 20px; /* Расстояние между изображением и текстом */
        }
    
        .image-section img {
            max-width: 100%; /* Изображение на всю ширину */
            height: auto; /* Сохраняем пропорции изображения */
        }
    
        .text-section {
            margin-top: 20px; /* Отступ сверху для текста */
        }
    }
    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }
    
    body {
        font-family: 'Roboto', sans-serif;
    }
    
    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 20px;
    }
    
    .image-text-container {
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 40px;
        margin-bottom: 40px;
    }
    
    .image-section img {
        max-width: 450px;
        height: auto;
        border-radius: 10px;
    }
    
    .text-section h1 {
        font-size: 24px;

        text-align: center;
        max-width: 300px;
    }
    
    .cards {
        display: flex;
        flex-wrap: wrap;
        gap: 20px;
        justify-content: center;
    }
    
    .card {
        background-color: white;
        padding: 20px;
        border-radius: 10px;
        width: 250px;
        display: flex;
        align-items: center;
        gap: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }
    
    .card input {
        max-width: 20px;
        height: 20px;
    }
    
    .card p {
        font-size: 16px;
        color: #333;
    }

    /* Основные стили для десктопной версии */
.image-text-section {
    display: grid;
    grid-template-columns: 1fr 1fr; /* Две колонки для изображений и текста */
    gap: 20px;
    padding: 20px;
}

.image-text-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
}

.section-image {
    max-width: 100%;
    height: auto;
}

.section-text {
    font-size: 1.2em;
    margin-top: 10px;
}

/* Стили для мобильных устройств */
@media (max-width: 768px) {
    .image-text-section {
        grid-template-columns: 1fr; /* Одна колонка на мобильных устройствах */
    }

    .image-text-container {
        margin-bottom: 20px;
    }

    .section-image {
        order: 1; /* Картинка сверху */
        
    }

    .section-text {
        order: 2; /* Текст снизу */
        font-size: 1em;
    
    }
}

    

/* From Uiverse.io by eslam-hany */ 
.card-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 20px; /* Расстояние между карточками */
    padding: 20px;
}

.cardU {
    width: 1020px;
    height: 120px;
    background: mediumturquoise;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 25px;
    font-weight: bold;
    border-radius: 15px;
    cursor: pointer;
    position: relative;
    overflow: hidden;
    transition: all 0.3s ease;
}

.cardU a {
    color: black;
    text-decoration: none;
}

.cardU a:first-child {
    position: relative;
    z-index: 1;
}

.cardU .read-more {
    position: absolute;
    bottom: 10px;
    right: 20px;
    font-size: 18px;
    color: white;
    text-decoration: underline;
    opacity: 0;
    transition: opacity 0.5s ease-in-out;
}

.cardU:hover .read-more {
    opacity: 1;
}

/* Адаптация для мониторов */
@media (min-width: 1024px) {
    .card-container {
        flex-direction: column; /* Одноколоночная структура на мониторах */
    }

    .cardU {
        width: 1320px;
        margin: 10px 0; /* Отступы между карточками */
    }
    .department-title {
        display: -webkit-box;
        -webkit-line-clamp: 1; /* Количество строк (можно указать 1 или больше) */
        -webkit-box-orient: vertical;
        overflow: hidden;
        text-overflow: ellipsis;
        font-size: 20px;
    }
}

/* Адаптация для телефонов */
@media (max-width: 768px) {
    .cardU {
        width: 90%; /* Уменьшение ширины для мобильных устройств */
        height: auto;
        font-size: 20px; /* Уменьшение размера текста */
        padding: 20px;
    }


    .cardU .read-more {
        bottom: 5px;
        right: 10px;
        font-size: 14px; /* Уменьшение размера текста для ссылок на мобильных */
    }

    /* Ограничение количества строк для заголовка */
    .department-title {
        display: -webkit-box;
        -webkit-line-clamp: 1; /* Количество строк (можно указать 1 или больше) */
        -webkit-box-orient: vertical;
        overflow: hidden;
        text-overflow: ellipsis;
        font-size: 18px;
    }
}

</style>
<br>
<h2 id="bolim" style="text-align: center; font-size: 60px;">{% trans "B'olimlar" %}</h2>
<br><hr><br><br>
<div class="card-container">
    {% for dep in departments %}
    <div class="cardU">
        <a class="department-title" href="{% url 'department_detail' dep.slug %}#dep">{{ dep.title }}</a>
        <a href="{% url 'department_detail' dep.slug %}" class="read-more">{% trans "Ko'proq bilib olish" %}</a>
    </div>
    {% endfor %}
</div>


<br><br>

<div class="container">
    <div class="image-text-container">
        <div class="image-section">
            <img src="{% static 'images/3.jpg' %}" alt="{% trans 'Worker' %}" class="image">
        </div>
        
        <div class="text-section">
            <h1>{% trans "Neft va gaz konlarini tadqiq etish bo'limi neft va gaz qazib olish konlarida:" %}</h1>
        </div>
    </div>
    <div class="cards">
        <div class="card">
            <input type="checkbox" checked disabled>
            <p>{% trans "ishlatilayotgan quduqlarning joriy mahsuldorlik xarakteristikalarini" %}</p>
        </div>
        <div class="card">
            <input type="checkbox" checked disabled>
            <p>{% trans "qazib olinayotgan gazning gaz-kondensat xarakteristikalarini" %}</p>
        </div>
        <div class="card">
            <input type="checkbox" checked disabled>
            <p>{% trans "quduqlarning joriy suv ko'rsatgichlarini" %}</p>
        </div>
        <div class="card">
            <input type="checkbox" checked disabled>
            <p>{% trans "quduqlarning qatlam bosimini hamda qazib olinayotgan neftning suvlanish darajasi" %}</p>
        </div>
    </div>
</div>


<section class="image-text-section">
    <div class="image-text-container">
        <img style="height: 400px;" src="{% static 'images/1_3.jpg' %}" alt="{% trans 'Image 1' %}" class="section-image">

        <div class="card">
            <input type="checkbox" checked disabled>
            <p>{% trans "Gazlar, gaz kondensatlari, neftlar va qatlam suvlari tadqiq etish masalasi." %}</p>
        </div>
    </div>
    <div class="image-text-container">
        <img src="{% static 'images/1_2.jpg' %}" alt="{% trans 'Image 2' %}" class="section-image">

        <div class="card">
            <input type="checkbox" checked disabled>
            <p>{% trans "Gazni tayyorlash, qayta ishlash va atrof muhitni muxofaza qilish boʻlimi." %}</p>
        </div>
    </div>
</section>


<div class="container">
    <div class="image-text-container">
        <div class="image-section">
            <img src="{% static 'images/1_1.jpg' %}" alt="Worker" class="image">
        </div>
        
        <div class="text-section">
            <h1>{% trans 'Kon uskunalari va quvurlarning ingibitorlik himoyasi bo‘limida' %}</h1>
        </div>
    </div>
    <div class="cards">
        <div class="card">
            <input type="checkbox" checked disabled>
            <p>{% trans 'ishlatilayotgan quduqlarning joriy mahsuldorlik xarakteristikalarini' %}</p>
        </div>
        <div class="card">
            <input type="checkbox" checked disabled>
            <p>{% trans 'metallning vodorodlanish darajasini' %}</p>
        </div>
        <div class="card">
            <input type="checkbox" checked disabled>
            <p>{% trans 'qo‘llanilayotgan ingibitorlarning samaradorligini aniqlash' %}</p>
        </div>
        <div class="card">
            <input type="checkbox" checked disabled>
            <p>{% trans 'tuproqning metallni yemirilishi xavfi yuqori bo‘lgan joylarini aniqlash' %}</p>
        </div>
    </div>
</div>
</div>
<br><br>
{% endblock %}

app/templates/department_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<br><br>
<div id="dep"></div>
<section class="department">
    <div class="department-content">
        <h1 class="department-title">{{ departments.title }}</h1>
        <p class="department-description">{{ departments.descriptions }}</p>
        
        {% if departments.img %}
            <div class="department-image">
                <img src="{{ departments.img.url }}" alt="{{ departments.title }}">
            </div>
        {% else %}
            <p class="no-image">{% trans 'Изображение отсутствует' %}</p>
        {% endif %}
    </div>
</section>
<br><br>

<style>
    .department {
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 20px;
        margin: 0 auto;
        max-width: 800px;
        text-align: center;
        background-color: #f5f5f5;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .department-title {
        font-size: 48px;
        margin: 10px 0;
        color: #333;
        font-family: 'Arial', sans-serif;
    }

    .department-description {
        font-size: 18px;
        line-height: 1.6;
        margin: 20px 0;
        color: #666;
        font-family: 'Georgia', serif;
    }

    .department-image {
        text-align: center; /* Центрирование блока с изображением */
        margin-top: 20px;
        display: flex; /* Используем flex для центрирования */
        justify-content: center; /* Центрируем содержимое по горизонтали */
    }

    .department-image img {
        max-width: 100%; /* Изображение не превышает ширину родительского элемента */
        height: auto; /* Высота изображения подстраивается под ширину */
        border-radius: 8px;
    }

    .no-image {
        font-style: italic;
        color: #999;
        margin-top: 20px;
    }

    @media (max-width: 600px) {
        .department {
            padding: 10px;
        }

        .department-title {
            font-size: 32px;
        }

        .department-description {
            font-size: 14px;
        }

        .department-image img {
            max-width: 90%; /* Чтобы изображение занимало 90% ширины на мобильных устройствах */
            margin: 0 auto; /* Центрирование изображения */
        }
    }
</style>
{% endblock %}

app/templates/finance.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

    <style>

        .table-container {
            width: 100%;
            overflow-x: auto;
            margin: 20px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            min-width: 800px; /* Минимальная ширина для корректного отображения на мобильных */
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: center;
            white-space: nowrap; /* Запрещаем перенос текста для корректного отображения */
        }
        th {
            background-color: #f4f4f4;
            color: #333;
            font-weight: bold;
        }
        .highlight {
            background: linear-gradient(90deg, #66a6ff 0%, #89f7fe 100%);
            color: white;
        }
        td {
            background: linear-gradient(90deg, #8e2de2 0%, #4a00e0 100%);
            color: white;
        }
        .section-title {
            font-weight: bold;
            text-align: left;
            background-color: #3a3a3a;
            color: white;
        }

        /* Мобильная адаптация */
        @media (max-width: 768px) {
            th, td {
                padding: 8px;
            }
            table {
                font-size: 12px;
            }
        }
        @media (max-width: 480px) {
            table {
                font-size: 10px;
            }
        }
    </style>

    <h2 style="text-align: center; font-size: 40px;" id="finances"> {% trans "2018 - 2020 yil yakunlari bo‘yicha «Neftgaztadqiqot» AJ asosiy moliyaviy-iqtisodiy ko‘rsatkichlari haqida ma'lumot" %}</h2>
    <br>
    <hr>
    <br>

    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th rowspan="2">{% trans "Ko'rsatkichlar" %}</th>
                    <th rowspan="2">Ед. изм.</th>
                    <th colspan="{{ years.count }}">{% trans "Faoliyat natijalari bo'yicha" %}</th>
                </tr>
                <tr>
                    {% for year in years %}
                        <th>{{ year.year }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for data in financial_data %}
                    <tr>
                        <td>{{ data.indicator_name }}</td>
                        <td>{{ data.unit }}</td>
                        {% for year in years %}
                            <td>
                                {% for value in data.financialyeardata_set.all %}
                                    {% if value.year.year == year.year %}
                                        {{ value.value }}
                                    {% endif %}
                                {% endfor %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>



{% endblock %}

app/templates/license.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
<br><br>
{% block content %}
    <div class="container my-5" id="license">
        <div class="card">
            <div class="card-header">
                <h2 class="h4">{% trans 'Akkreditsiya' %}</h2>
            </div>
            <div class="card-body">
                <p class="mb-4">{% trans "Ushbu bo‘limda siz kompaniyangizning Akkreditsiya hujjatining PDF-fayllarini ko‘rishingiz yoki yuklab olishingiz mumkin. Biz shaffoflikka ahamiyat beramiz va faoliyatimizga bo‘lgan ishonchingiz uchun barcha зарур hujjatlarni taqdim etamiz." %}</p>

                <!-- Отображаем все лицензии -->
                {% for license in licenses %}
                    {% if license.pdf %}
                        <div class="embed-responsive embed-responsive-16by9 mb-4">
                            <embed src="{{ license.pdf.url }}" type="application/pdf" class="embed-responsive-item" />
                        </div>

                        <!-- Кнопка скачивания с отступом -->
                        <a href="{{ license.pdf.url }}" class="btn btn-primary mb-4" target="_blank">{% trans 'PDF Akkreditsiyani yuklab olish' %}</a>
                    {% else %}
                        <p>{% trans 'Akkreditsiya hujjati mavjud emas' %}</p>
                    {% endif %}
                    
                    <!-- Разделитель для визуального разделения лицензий -->
                    <hr class="my-4">
                {% endfor %}
            </div>
        </div>
    </div>
    <br><br>
{% endblock %}

app/templates/structure.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="container" id="structure">
    <h1 class="page-title">{% trans "AO 'Neftgaztadqiqot' AJ tashkiliy tuzilmasi" %}</h1>
    <div class="image-container">
        <img src="{% static 'images/structure.png' %}" alt="{% trans 'Structure Image' %}" class="structure-image">
    </div>
    <hr>
    <div class="text-content">
        <p>
            {% trans ' "Neftgaztadqiqot" AJning Oliy boshqaruv organi aksiyadorlarning Umumiy yig‘ilishi hisoblanadi. Umumiy yig‘ilish tomonidan saylanadigan Kuzatuv kengashi jamiyatning umumiy rahbarligini amalga oshirib, faoliyatning ustivor yo‘nalishlarini, rivojlanish istiqbollari va strategiyasini aniqlab beradi, hamda jamiyat oldida turgan yaqin muddatdagi maqsadlarni va ularga erishish taktikasini ishlab chiqadi. Joriy rahbarlik kollegial ijroya organi – Boshqaruv, tomonidan amalga oshirilib, mazkur organ Umumiy yig‘ilish va Kuzatuv kengashi tomonidan qabul qilingan qarorlarning bajarilishini tashkillashtiradi va nazorat qiladi.' %}
        </p>
    </div>
</div>

<style>
        /* Контейнер для содержимого */
    .container {
        max-width: 900px;
        margin: 0 auto;
        padding: 20px;
    }

    /* Заголовок страницы */
    .page-title {
        font-size: 2.5rem;
        font-weight: bold;
        color: #333;
        text-align: center;
        margin-bottom: 20px;
    }

    /* Контейнер для изображения */
    .image-container {
        text-align: center;
        margin-bottom: 20px;
    }

    /* Изображение структуры */
    .structure-image {
        max-width: 100%;
        height: auto;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    /* Текстовый контент */
    .text-content {
        font-size: 1rem;
        line-height: 1.6;
        color: #555;
        text-align: justify;
    }

    .text-content p {
        margin: 0;
    }

</style>
{% endblock content %}